export const FEEDS = [
  { name: "Stripe Engineering", url: "https://stripe.com/blog/feed.rss" },
  { name: "Cloudflare", url: "https://blog.cloudflare.com/rss/" },
  { name: "Netflix TechBlog", url: "https://netflixtechblog.com/feed" },
  { name: "Discord Engineering", url: "https://discord.com/blog/rss.xml" },
  { name: "Figma", url: "https://www.figma.com/blog/feed/atom.xml" },
  { name: "Vercel", url: "https://vercel.com/atom" },
  { name: "Shopify Engineering", url: "https://shopify.engineering/blog.atom" },
  { name: "GitHub Engineering", url: "https://github.blog/engineering/feed/" },
  { name: "Meta Engineering", url: "https://engineering.fb.com/feed/" },
  { name: "Dan Abramov", url: "https://overreacted.io/rss.xml" },
  { name: "Kent C. Dodds", url: "https://kentcdodds.com/blog/rss.xml" },
  { name: "Julia Evans", url: "https://jvns.ca/atom.xml" },
  { name: "Martin Fowler", url: "https://martinfowler.com/feed.atom" },
  { name: "Simon Willison", url: "https://simonwillison.net/atom/everything/" },
  { name: "Matt Pocock", url: "https://www.totaltypescript.com/rss.xml" },
  { name: "Effect", url: "https://effect.website/rss.xml" },
  { name: "Bun", url: "https://bun.sh/rss.xml" },
  { name: "TypeScript", url: "https://devblogs.microsoft.com/typescript/feed/" },
] as const
